Simplify. FEATURES and CFLAGS should be chroot-wide.

diff --git a/generate b/generate
--- a/generate
+++ b/generate
@@ -7,13 +7,20 @@
 # What you can set:
 VERSION="4.1.3.2"
 BINVERSION="4.1.3.2"
-OPTS="-v"
-USEFILE="/etc/portage/package.use/libreo"
-MYPKGDIR="$( portageq pkgdir )"
-MYTMPDIR=/root/tmp
-MYDISTDIR=/root/distfiles
 
 ################################################
+
+BASEDIR=/root/lo-bin-build
+
+USEFILE="/etc/portage/package.use/libreo"
+MYPKGDIR="$( portageq pkgdir )"
+MYTMPDIR=$BASEDIR/tmp
+MYDISTDIR=$BASEDIR/distfiles
+
+################################################
+
+
+OPTS="-v"
 
 # bug 473974
 export LC_MESSAGES=C
@@ -24,30 +31,12 @@ die() {
 }
 
 if [ "$( uname -m )" = "x86_64" ] ; then
-	MYFLAGS="-march=x86-64 -mtune=generic -O2 -pipe -g"
 	ARCH="amd64"
 elif [ "$( uname -m )" = "i686" ] ; then
-	MYFLAGS="-march=i586 -mtune=generic -O2 -pipe -g"
 	ARCH="x86"
 else
 	die "Arch $( uname -m ) not supported"
 fi
-
-for i in \
-	"/bin/echo" \
-	"/bin/mkdir" \
-	"/bin/mv" \
-	"/bin/rm" \
-	"/bin/sed" \
-	"/bin/tar" \
-	"/usr/bin/emerge" \
-	"/usr/bin/portageq" \
-	"/usr/bin/quickpkg"
-do
-	if [ ! -e "${i}" ] ; then
-		die "Missing some basic utility in your system"
-	fi
-done
 
 # first the default subset of useflags
 IUSES_BASE="bash-completion branding cups dbus gstreamer gtk opengl vba webdav -aqua -binfilter -bluetooth -debug -gtk3 -jemalloc -mysql -odk -postgres -telepathy"
@@ -85,39 +74,39 @@ fi
 # compile the flavor
 echo "Base"
 echo "app-office/libreoffice ${IUSES_BASE} ${IUSES_NJ} ${IUSES_NG} ${IUSES_NK}" > ${USEFILE}
-FEATURES="${FEATURES} splitdebug" CFLAGS="${MYFLAGS}" CXXFLAGS="${MYFLAGS}" emerge ${OPTS} =libreoffice-${VERSION} || die "emerge failed"
+emerge ${OPTS} =libreoffice-${VERSION} || die "emerge failed"
 quickpkg libreoffice --include-config=y
 mv ${MYPKGDIR}/app-office/libreoffice-${VERSION}.tbz2 ${MYTMPDIR}/libreoffice-base-${BINVERSION}.tbz2  || die "Moving package failed"
 
 echo "Base - java"
 echo "app-office/libreoffice ${IUSES_BASE} ${IUSES_J} ${IUSES_NG} ${IUSES_NK}" > ${USEFILE}
-FEATURES="${FEATURES} splitdebug" CFLAGS="${MYFLAGS}" CXXFLAGS="${MYFLAGS}" emerge ${OPTS} =libreoffice-${VERSION} || die "emerge failed"
+emerge ${OPTS} =libreoffice-${VERSION} || die "emerge failed"
 quickpkg libreoffice --include-config=y
 mv ${MYPKGDIR}/app-office/libreoffice-${VERSION}.tbz2 ${MYTMPDIR}/libreoffice-base-java-${BINVERSION}.tbz2  || die "Moving package failed"
 
 # kde flavor
 echo "KDE"
 echo "app-office/libreoffice ${IUSES_BASE} ${IUSES_NJ} ${IUSES_NG} ${IUSES_K}" > ${USEFILE}
-FEATURES="${FEATURES} splitdebug" CFLAGS="${MYFLAGS}" CXXFLAGS="${MYFLAGS}" emerge ${OPTS} =libreoffice-${VERSION} || die "emerge failed"
+emerge ${OPTS} =libreoffice-${VERSION} || die "emerge failed"
 quickpkg libreoffice --include-config=y
 mv ${MYPKGDIR}/app-office/libreoffice-${VERSION}.tbz2 ${MYTMPDIR}/libreoffice-kde-${BINVERSION}.tbz2  || die "Moving package failed"
 
 echo "KDE - java"
 echo "app-office/libreoffice ${IUSES_BASE} ${IUSES_J} ${IUSES_NG} ${IUSES_K}" > ${USEFILE}
-FEATURES="${FEATURES} splitdebug" CFLAGS="${MYFLAGS}" CXXFLAGS="${MYFLAGS}" emerge ${OPTS} =libreoffice-${VERSION} || die "emerge failed"
+emerge ${OPTS} =libreoffice-${VERSION} || die "emerge failed"
 quickpkg libreoffice --include-config=y
 mv ${MYPKGDIR}/app-office/libreoffice-${VERSION}.tbz2 ${MYTMPDIR}/libreoffice-kde-java-${BINVERSION}.tbz2  || die "Moving package failed"
 
 # gnome flavor
 echo "Gnome"
 echo "app-office/libreoffice ${IUSES_BASE} ${IUSES_NJ} ${IUSES_G} ${IUSES_NK}" > ${USEFILE}
-FEATURES="${FEATURES} splitdebug" CFLAGS="${MYFLAGS}" CXXFLAGS="${MYFLAGS}" emerge ${OPTS} =libreoffice-${VERSION} || die "emerge failed"
+emerge ${OPTS} =libreoffice-${VERSION} || die "emerge failed"
 quickpkg libreoffice --include-config=y
 mv ${MYPKGDIR}/app-office/libreoffice-${VERSION}.tbz2 ${MYTMPDIR}/libreoffice-gnome-${BINVERSION}.tbz2  || die "Moving package failed"
 
 echo "Gnome -java"
 echo "app-office/libreoffice ${IUSES_BASE} ${IUSES_J} ${IUSES_G} ${IUSES_NK}" > ${USEFILE}
-FEATURES="${FEATURES} splitdebug" CFLAGS="${MYFLAGS}" CXXFLAGS="${MYFLAGS}" emerge ${OPTS} =libreoffice-${VERSION} || die "emerge failed"
+emerge ${OPTS} =libreoffice-${VERSION} || die "emerge failed"
 quickpkg libreoffice --include-config=y
 mv ${MYPKGDIR}/app-office/libreoffice-${VERSION}.tbz2 ${MYTMPDIR}/libreoffice-gnome-java-${BINVERSION}.tbz2  || die "Moving package failed"
 
